POST http://172.18.0.4:3000/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiQnJhZEBnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE2ODI0MTI0ODYsImV4cCI6MTY4NTAwNDQ4Nn0.Lf4GjKFRvLadHqWasI1Nzyl6Mhisg0asRqgVisEtNlY"
}