POST http://172.18.0.4:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "firstName": "Brad",
  "lastName": "Pitt",
  "displayName": "Brad",
  "password": "123123",
  "email": "Brad@gmail.com",
  "role": "customer"
}